<?php
  $lang['number']		= 'Invoice No';
  $lang['date'] 		= 'Billing month';
  $lang['time']			= 'CUSTOMER ID';
  $lang['due'] 			= 'Due date';
  $lang['to'] 			= 'Billing to';
  $lang['from'] 		= 'Billing from';
  $lang['product'] 		= 'Orders';
  $lang['qty'] 			= 'Qty';
  $lang['price'] 		= 'Price';
  $lang['discount']     = 'Discount';
  $lang['vat'] 			= 'Vat';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Page';
  $lang['page_of'] 		= 'of';
  $lang['sl']           = 'SL';
